const store=require('../../services/store');const config=require('../../config');
Page({data:{ready:false,editing:false,busy:false,draft:{},regionText:'',placeBusy:false,foldLabels:['自动判断','重复时刻：第一次','重复时刻：第二次'],foldIndex:0,error:'',today:'',content:null,local:config.localDeveloperLogin},
 onLoad(){const d=new Date();this.setData({today:[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')})},
 async onShow(){if(getApp().boot)await getApp().boot;const s=store.read();const ready=store.canRead(s);this.setData({ready,draft:s.draft,profile:s.profile,member:s.member,regionText:s.draft.region.join(' · '),editing:false,content:null,error:getApp().globalData.bootError||'',foldIndex:s.draft.fold===null?0:s.draft.fold+1})},
 change(e){const key=e.currentTarget.dataset.key;const patch={[key]:e.detail.value};store.patchDraft(patch);this.setData({draft:store.read().draft,error:''})},
 region(e){const region=e.detail.value;if(['香港特别行政区','澳门特别行政区','台湾省'].includes(region[0])){this.setData({error:'目前仅支持中国大陆地区'});return}store.patchDraft({region,placeToken:'',placeLabel:''});this.setData({draft:store.read().draft,regionText:region.join(' · ')});this.place()},
 async place(){const seq=this.placeSeq=(this.placeSeq||0)+1;const d=store.read().draft;if(!d.consent||d.region.length<2){this.setData({placeBusy:false});return}const address=d.region.join('');this.setData({placeBusy:true,error:''});try{const result=await store.resolvePlace(address);if(seq!==this.placeSeq||!store.read().draft.consent||address!==store.read().draft.region.join(''))return;store.patchDraft(result);this.setData({draft:store.read().draft})}catch(e){if(seq===this.placeSeq)this.setData({error:e.message+'；请重新选择地区重试'})}finally{if(seq===this.placeSeq)this.setData({placeBusy:false})}},
 analysis(e){wx.navigateTo({url:'/pages/analysis/index?kind='+e.currentTarget.dataset.kind})},
 async save(){try{await store.authenticated('/v1/history','POST',{});wx.showToast({title:'记录已保存'})}catch(e){wx.showToast({title:e.message,icon:'none'})}},
 fold(e){const v=Number(e.detail.value);store.patchDraft({fold:v===0?null:v-1});this.setData({foldIndex:v})},
 consent(e){store.patchDraft({consent:e.detail.value.includes('yes')});this.setData({draft:store.read().draft});this.place()},
 async submit(){if(this.data.busy||this.data.placeBusy)return;this.setData({busy:true,error:''});try{await store.saveProfile();wx.switchTab({url:'/pages/chart/index'})}catch(e){this.setData({error:e.message})}finally{this.setData({busy:false})}},
 async login(){if(this.data.busy)return;this.setData({busy:true,error:''});try{await store.signIn();this.onShow()}catch(e){this.setData({error:e.message})}finally{this.setData({busy:false})}},
 edit(){store.patchDraft(store.read().profile);this.setData({editing:true,draft:store.read().draft,error:''})},cancel(){this.setData({editing:false})},chart(){wx.switchTab({url:'/pages/chart/index'})},calendar(){wx.switchTab({url:'/pages/calendar/index'})},report(e){wx.navigateTo({url:'/pages/report/index?type='+e.currentTarget.dataset.type})},about(){wx.navigateTo({url:'/pages/about/index'})}
})
