const store=require('../../services/store');const {validate,empty}=require('../../services/domain');
Page({data:{ready:false,kind:'natal',period:'',busy:false,error:'',result:null,consent:false,partner:empty().draft,regionText:'',jobId:'',history:false,foldIndex:0,foldLabels:['自动判断','重复时刻：第一次','重复时刻：第二次']},
 onLoad(q){this.hid=q.id;const kind=['natal','transit','month','year','synastry'].includes(q.kind)?q.kind:'natal';this.setData({kind,period:q.period||new Date().toISOString().slice(0,kind==='year'?4:7)})},
 async onShow(){this.hidden=false;const s=store.read();this.setData({ready:store.canRead(s),member:s.member});if(this.hid){try{const record=await store.authenticated('/v1/history/'+encodeURIComponent(this.hid));this.setData({ready:true,history:true,result:record.analysis||{title:'已保存的星盘',summary:record.profile.date+' '+record.profile.time+' '+record.profile.placeLabel,sections:record.chart.planets.map(p=>({title:p.name,text:p.sign+' '+p.degree+'°',basis:'历史星盘计算结果'}))}})}catch(e){this.setData({error:e.message})}}else if(this.data.jobId&&this.data.busy)this.poll()},
 onHide(){this.hidden=true;clearTimeout(this.timer)},onUnload(){this.dead=true;clearTimeout(this.timer)},
 agree(e){this.setData({consent:e.detail.value.includes('yes')});if(this.data.kind==='synastry')this.place()},
 change(e){const key=e.currentTarget.dataset.key;const p=Object.assign({},this.data.partner,{[key]:e.detail.value});this.setData({partner:p})},
 fold(e){const i=Number(e.detail.value);this.setData({foldIndex:i,partner:Object.assign({},this.data.partner,{fold:i===0?null:i-1})})},
 region(e){this.setData({partner:Object.assign({},this.data.partner,{region:e.detail.value,placeToken:'',placeLabel:''}),regionText:e.detail.value.join(' · ')});this.place()},
 period(e){this.setData({period:e.detail.value,result:null,jobId:''})},
 async place(){const seq=this.placeSeq=(this.placeSeq||0)+1;const p=this.data.partner;if(!this.data.consent||p.region.length<2){this.setData({placeBusy:false});return}const address=p.region.join('');this.setData({error:'',placeBusy:true});try{const place=await store.resolvePlace(address);if(seq!==this.placeSeq||!this.data.consent||address!==this.data.partner.region.join(''))return;this.setData({partner:Object.assign({},this.data.partner,place)})}catch(e){if(seq===this.placeSeq)this.setData({error:e.message+'；请重新选择地区重试'})}finally{if(seq===this.placeSeq)this.setData({placeBusy:false})}},
 async generate(){if(this.data.busy||this.data.placeBusy)return;if(!this.data.consent){this.setData({error:'请先同意 AI 分析说明'});return}let partner=null;if(this.data.kind==='synastry'){const p=Object.assign({},this.data.partner,{consent:true});const error=validate(p);if(error){this.setData({error});return}partner=store.birth(p)}this.setData({error:'',busy:true,result:null});try{const job=await store.authenticated('/v1/ai/jobs','POST',{kind:this.data.kind,period:this.data.period,consent:true,partner});this.setData({jobId:job.jobId});this.poll()}catch(e){this.setData({error:e.message,busy:false})}},
 async poll(){clearTimeout(this.timer);if(this.dead||this.hidden)return;try{const job=await store.authenticated('/v1/ai/jobs/'+this.data.jobId);if(this.dead)return;if(job.status==='done'){this.setData({result:job.result,busy:false});return}if(job.status==='failed'){this.setData({error:job.result.message,busy:false});return}if(!this.hidden)this.timer=setTimeout(()=>this.poll(),2000)}catch(e){if(!this.dead)this.setData({error:e.message,busy:false})}},
 async save(){try{await store.authenticated('/v1/history','POST',{jobId:this.data.jobId});wx.showToast({title:'已保存到会员记录'})}catch(e){wx.showToast({title:e.message,icon:'none'})}},home(){wx.switchTab({url:'/pages/home/index'})}
})
