// Generated by tools/sync_release.py; edit release.json.
module.exports = {
  "version": "0.5.0",
  "apiVersion": 1,
  "sourceUrl": "https://github.com/RachelShi-202/jyoti-miniapp",
  "cloudEnv": "prod-d8gketm9db0dc7ea0",
  "cloudService": "jyoti-api"
};
