// Generated by tools/sync_release.py; edit release.json.
module.exports = {
  "version": "0.4.3",
  "apiVersion": 1,
  "sourceUrl": "https://github.com/RachelShi-202/jyoti-miniapp",
  "cloudEnv": "prod-d5gxm0gh7f246e8f0",
  "cloudService": "jyoti-api"
};
