"""Single source of truth for frontend and backend release identity."""
import json,argparse
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
r=json.loads((ROOT/'release.json').read_text())
outputs={
 'miniprogram/release-config.js':'// Generated by tools/sync_release.py; edit release.json.\nmodule.exports = '+json.dumps(r,ensure_ascii=False,indent=2)+';\n',
 'backend/release_info.py':'# Generated by tools/sync_release.py; edit release.json.\nRELEASE = '+repr(r['version'])+'\nAPI_VERSION = '+repr(r['apiVersion'])+'\nSOURCE_URL = '+repr(r['sourceUrl'])+'\n',
}
def sync(check=False):
 for name,text in outputs.items():
  p=ROOT/name
  if check:
   if not p.exists() or p.read_text()!=text:raise SystemExit('Release mismatch: '+name)
  else:p.write_text(text)
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args();sync(a.check)
